version: '3.7'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8001:9000"
    volumes:
      - ./docker/:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ...
      MYSQL_DATABASE: ...
      MYSQL_USER: ...
      MYSQL_PASSWORD: ...
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
